version: '3'
services:
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox_engine
    ports:
      - '50021:50021'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048m
    logging:
      driver: json-file
      options:
        max-size: 10k
    expose:
      - '50021'
    tty: true
    stdin_open: true
    networks:
      - voicevox_network

networks:
  voicevox_network: