version: '3'
services:
  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    container_name: voicevox-engine
    ports:
      - '50021:50021'
    expose:
      - '8080'
    tty: true
    stdin_open: true