@echo off
echo Setting up virtual environment...
python -m venv env
echo Activating virtual environment...
call env\Scripts\activate
echo Upgrading pip...
env\Scripts\python.exe -m pip install --upgrade pip
echo Installing required libraries...
pip install -r requirements.txt
echo Installation complete.
pause
